name: Check stack

on:
  push:

jobs:
  check-stack:
    name: Check pulumi stack
    runs-on: ubuntu-latest
    outputs:
      SHOULD_CREATE_STACK: ${{ steps.select-stack.outcome == 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if stack exists
        id: select-stack
        continue-on-error: true
        run: |
          exit 1;

  create-stack:
    name: Create PR stack
    runs-on: ubuntu-latest
    needs: check-stack
    if: needs.check-stack.outputs.SHOULD_CREATE_STACK
    steps:
      - run: echo creating

  remove-stack:
    name: Remove PR stack
    runs-on: ubuntu-latest
    needs: check-stack
    if: needs.check-stack.outputs.SHOULD_CREATE_STACK == false
    steps:
      - run: echo "already exists, delete!"
