name: Check stack

on:
  push:

jobs:
  check-stack:
    name: Check pulumi stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if stack exists
        id: select-stack
        run: |
          exit 1;

  create-stack:
    name: Create PR stack
    runs-on: ubuntu-latest
    needs: check-stack
    if: failure()
    steps:
      - run: echo creating

  remove-stack:
    name: Remove PR stack
    runs-on: ubuntu-latest
    needs: check-stack
    if: success()
    steps:
      - run: echo "already exists, delete!"
