name: Trigger - PR build on comment

env:
  DOCKER_SERVER: registry.knatofs.se
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

on:
  issue_comment:
    types:
      - created

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: hard code
        run: echo "STACK_NAME_1="$(echo "${{ github.event.comment.body }}" | grep -oE '(pr-[0-9]*)') >> $GITHUB_ENV
  call-pr-build:
      needs: set-vars
      if: ${{ startsWith(github.event.comment.body, 'deploy') }}
      uses: ./.github/workflows/pr-build.yaml
      with:
        pr-number: hard-coded-pr-number
        stack-name: echo "${{ github.event.comment.body }}" | grep -oE '(pr-[0-9]*)'


