name: Do something on comments

on:
  issue_comment:
    types:
      - created
jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'deploy'}}
    env:
      BRANCH: ${{ github.ref_name }}
      PR_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Test something
        run: |
          echo "PullRequest nr $PR_NUMBER";
          echo "Branch name $BRANCH";