name: Trigger - PR build on comment

env:
  DOCKER_SERVER: registry.knatofs.se
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

on:
  issue_comment:
    types:
      - created

jobs:
  call-pr-build:
      if: ${{ startsWith(github.event.comment.body, 'deploy') }}
      runs-on: ubuntu-latest
      steps:
        - name: Set variables
          env:
            what: ${{ github.event.comment.body }} | grep -oE '(pr-[0-9]*)'
          uses: ./.github/workflows/pr-build.yaml
          with:
            pr-number: ${{ github.event.comment.body }} | grep -oE '(pr-[0-9]*)'
            stack-name: pr-${{ what }}


