name: Trigger - PR build on comment

env:
  DOCKER_SERVER: registry.knatofs.se
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1

on:
  issue_comment:
    types:
      - created

jobs:
  set-vars:
    if: ${{ startsWith(github.event.comment.body, 'deploy') }}
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.add-values.outputs.pr-number }}
      stack-name: ${{ steps.add-values.outputs.stack-name }}
    steps:
      - name: Add values to outputs
        id: add-values
        run: |
          echo "pr-number="$(echo "${{ github.event.comment.body }}" | grep -oE 'pr-([0-9]+)' | sed 's/pr-//') >> $GITHUB_OUTPUT
          echo "stack-name="$(echo "${{ github.event.comment.body }}" | grep -oE '(pr-[0-9]+)') >> $GITHUB_OUTPUT
      - uses: octokit/request-action@v2.x
        id: get-pr
        with:
          route: GET /repos/johannestretton37/actions/pulls/${{ steps.add-values.outputs.pr-number }}
          owner: johannestretton37
          repo: actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo PR sha: ${{ steps.get-pr.outputs.head.sha }}"
  call-pr-build:
      needs: set-vars
      uses: ./.github/workflows/pr-build.yaml
      if: ${{ startsWith(github.event.comment.body, 'deploy') }}
      with:
        pr-number: ${{ needs.set-vars.outputs.pr-number }}
        stack-name: ${{ needs.set-vars.outputs.stack-name }}

