name: Trigger - PR build on comment

env:
  DOCKER_SERVER: registry.knatofs.se
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

on:
  issue_comment:
    types:
      - created

jobs:
  set-vars:
    if: ${{ startsWith(github.event.comment.body, 'deploy') }}
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.add-values.outputs.pr-number }}
    steps:
      - name: Add values to outputs
        id: add-values
        run: echo "pr-number="$(echo "${{ github.event.comment.body }}" | grep -oE '(pr-[0-9]*)') >> $GITHUB_OUTPUT
  call-pr-build:
      needs: set-vars
      uses: ./.github/workflows/pr-build.yaml
      if: ${{ startsWith(github.event.comment.body, 'deploy') }}
      with:
        pr-number: ${{ needs.set-vars.outputs.pr-number }}


