name: Trigger - PR build on comment

env:
  DOCKER_SERVER: registry.knatofs.se
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1

on:
  issue_comment:
    types:
      - created

jobs:
  set-vars:
    if: ${{ startsWith(github.event.comment.body, 'deploy') }}
    runs-on: ubuntu-latest
    outputs:
      git-sha: ${{ fromJson(steps.get-pr.outputs.data).head.sha }}
    steps:
      - name: debug event                     #
        run: echo ${{ toJson(github.event) }} #
      - name: get pull request info
        id: get-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/johannestretton37/actions/pulls/${{ github.event.issue.number }}
  call-pr-build:
      needs: set-vars
      uses: ./.github/workflows/pr-build.yaml
      if: ${{ startsWith(github.event.comment.body, 'deploy') }}
      with:
        pr-number: ${{ github.event.issue.number }}
        git-sha: ${{ needs.set-vars.outputs.git-sha }}

