name: Publish performance report result

on:
  repository_dispatch:
    types:
      - puppet-result

jobs:
  puppet-report:
    runs-on: ubuntu-latest
    steps:
    # - name: Use Node.js 18
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18.x'
    #     cache: npm
      - name: 'Echo test group id'
        run: 'echo "Test group ${{ github.event.client_payload.testGroupId }} completed."'
      - name: 'Github Script v5 test'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # issue_number: context.issue.number,
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.client_payload.pullRequestId,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🕹  Puppet tool has _completed_ **all tests** in group ${{ context.payload.client_payload.testGroupId }}!
              
              And here's a new line...`
            })
            