name: Publish performance report result

on:
  repository_dispatch:
    types:
      - puppet-result

jobs:
  puppet-report:
    runs-on: ubuntu-latest
    steps:
    # - name: Use Node.js 18
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18.x'
    #     cache: npm
    - run: 'echo "Test group ${{ github.event.client_payload.testGroupId }} completed"'
