name: Reusable - Pull Request build and deploy

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      stack-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ inputs.pr-number }}
      STACK_NAME: ${{ inputs.stack-name }}
    steps:
      - name: set vars
        run: echo "STACK_NAME="$(echo "${{ github.event.comment.body }}" | grep -oE '(pr-[0-9]*)') >> $GITHUB_ENV
      - name: debug it
        run: |
          echo PR_NUMBER $PR_NUMBER
          echo STACK_NAME $STACK_NAME
          echo STACK_NAME_1 $STACK_NAME_1
        
