name: Reusable - Pull Request build and deploy

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      git-sha:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ inputs.pr-number }}
      GIT_SHA: ${{ inputs.git-sha }}
    steps:
      - uses: actions/checkout@v3
      - name: debug inputs
        run: |
          echo "PR_NUMBER from previous step -> $PR_NUMBER";
          echo "GIT_SHA from previous step -> $GIT_SHA";
        
