name: Reusable - Pull Request build and deploy

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      stack-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ inputs.pr-number }}
      STACK_NAME: ${{ inputs.stack-name }}
    steps:
      - name: debug it
        run: |
          echo "PR_NUMBER from previous step -> $PR_NUMBER";
          echo "STACK_NAME from previous step -> $STACK_NAME";
        
