name: Pull request base image builder
on:
  pull_request:
    branches: [main, master] # PR targets main/master branch
    types: [opened] # Only triggered when PR is created
jobs:
  build-base-image:
    if:  startsWith(github.head_ref, 'performance/') # Only run if PR branch has "performance/" prefix
    runs-on: ubuntu-latest
    env:
      PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Build base image
        run: |
          echo "TODO: - build and deploy an image so we can compare with something. \
          git should checkout this commit -> $PR_BASE_SHA"
      - uses: actions/checkout@v3
        with:
          ref: ${{ $PR_BASE_SHA }}
      - name: Debug
        run: ls

