name: Publish package

on:
  release:
    types:
      - "published"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish ${{ toJSON(github.event.release.tag_name) }} to npm
        run: |
          echo "Publishing ${{ toJSON(github.event) }}"