name: Quick test

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          export IMAGE_TAG=$(git rev-parse --short=7 HEAD)
          echo "IMAGE_TAG=hahahaha$IMAGE_TAG" >> $GITHUB_ENV
          buildDate=$(date) ./build.sh

      - name: echo
        run: |
          echo "IMAGE_TAG  \`${{ github.env.IMAGE_TAG || '' }}\`" >> $GITHUB_STEP_SUMMARY
