name: Quick test
run-name: Deploy ${{ github.ref_name }} and ${{ inputs.first }}

on:
  push:
  workflow_dispatch:
    inputs:
      first:
        description: first
        type: string
      second:
        description: second
        type: string

jobs:
  first:
    runs-on: ubuntu-latest
    if: inputs.first
    steps:
      - name: First job
        run: echo "first"
  second:
    runs-on: ubuntu-latest
    needs: first
    if: always() && inputs.second
    steps:
      - name: Second job
        run: echo "second"
