on:
  push:

jobs:
  conditions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Diff files in apps dir
        run: echo DIFF=$(./diff-files.sh apps) >> $GITHUB_ENV
      - name: Something has changed
        continue-on-error: true
        if: ${{ env.DIFF > 0 }}
        run: echo env.DIFF ${{ env.DIFF }}
  waiting:
      runs-on: ubuntu-latest
      steps:
      - name: joke
        continue-on-error: true
        run: |
          echo $(curl -H "Accept: text/plain" https://icanhazdadjoke.com) >> $GITHUB_STEP_SUMMARY
  echoer:
      runs-on: ubuntu-latest
      steps:
      - name: deploy
        id: rollout
        run: |
          echo urlsDict='{"dk": "https://pinocchio-dk.elkds-dev.example.com","fi": "https://pinocchio-fi.elkds-dev.example.com","no": "https://pinocchio-no.elkds-dev.example.com","se": "https://pinocchio-se.elkds-dev.example.com"}' >> $GITHUB_OUTPUT
      - name: display info
        run: |
          echo -e "## Pinocchio :lying_face: URLs (Dev)\n
          [Admin NO :norway:](${{ fromJSON(steps.rollout.outputs.urlsDict).no }}/admin)
          [Proxy NO :norway:](${{ fromJSON(steps.rollout.outputs.urlsDict).no }})\n
          [Admin SE :sweden:](${{ fromJSON(steps.rollout.outputs.urlsDict).se }}/admin)
          [Proxy SE :sweden:](${{ fromJSON(steps.rollout.outputs.urlsDict).se }})\n
          [Admin DK :denmark:](${{ fromJSON(steps.rollout.outputs.urlsDict).dk }}/admin)
          [Proxy DK :denmark:](${{ fromJSON(steps.rollout.outputs.urlsDict).dk }})\n
          [Admin FI :finland:](${{ fromJSON(steps.rollout.outputs.urlsDict).fi }}/admin)
          [Proxy FI :finland:](${{ fromJSON(steps.rollout.outputs.urlsDict).fi }})" >> $GITHUB_STEP_SUMMARY

  nope:
    if: "!endsWith(github.actor, '[bot]')"
    runs-on: ubuntu-latest
    steps:
      - name: does not end with bot
        run: echo "Actor does not end with bot"
  yep:
    if: "endsWith(github.actor, '[bot]')"
    runs-on: ubuntu-latest
    steps:
      - name: does end with bot
        run: echo "Actor does not end with bot"

