name: Trigger Puppet

on:
  pull_request:
    branches:
      - main
      - performance/*
    
jobs:
  trigger-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Build PR branch
        run: |
          echo 'TODO: Build this branch to a unique URL and store URL as env var';
          export DEPLOYED_PR_URL=https://elk.tornberg.me
          echo "COMPARE_URL=$DEPLOYED_PR_URL" >> $GITHUB_ENV
      - name: Trigger a test run in 🕹 Puppet
        env:
          # This should be an endpoint in the puppet tool, /api/tests/init
          URL: 'https://b82c-95-192-87-112.eu.ngrok.io/api/tests/init'
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          TEST_TO_RUN: "startPageToPdp"
          BASE_URL: "https://elk-org.tornberg.me" # Should this be hard coded?
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # -H "Authorization: token $GITHUB_TOKEN" \
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            --data "{ \"pullRequestId\": \"$PR_NUMBER\", \"sha\": \"$PR_HEAD_SHA\", \"baseUrl\": \"$BASE_URL\", \"compareUrl\": \"$COMPARE_URL\", \"numberOfTests\": 3, \"testName\": \"$TEST_TO_RUN\" }"
