name: Trigger Puppet

on:
  pull_request:
    branches:
      - main
      - performance/*
    
jobs:
  trigger-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Build PR branch
        run: |
          echo 'TODO: Build this branch to a unique URL and store URL as env var';
          DEPLOYED_PR_URL=https://elk.tornberg.me
          echo "BASE_URL=$DEPLOYED_PR_URL" >> $GITHUB_ENV
      - name: Trigger a test run in 🕹 Puppet
        env:
          # This should be an endpoint in the puppet tool, /api/tests/init
          URL: 'https://webhook.site/8850c101-12d1-40f4-8604-8a7af1163e74'
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          TEST_TO_RUN: "someTestName"
          BASE_URL: ${{ env.baseUrl }}
          COMPARE_URL: "https://master.branch" # Should this be hard coded?
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # -H "Authorization: token $GITHUB_TOKEN" \
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            --data "{ \"pullRequestId\": \"$PR_NUMBER\", \"sha\": \"$PR_HEAD_SHA\", \"baseUrl\": \"$BASE_URL\", \"numberOfTests\": 3 }"
