name: Trigger Puppet

on:
  pull_request:
    branches:
      - main
      - performance/**
    
jobs:
  trigger-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Call Puppet Tool
        env:
          URL: 'https://webhook.site/8850c101-12d1-40f4-8604-8a7af1163e74'
          # URL: ${{ github.event.issue.comments_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # -H "Authorization: token $GITHUB_TOKEN" \
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            --data "{ \"pullRequestId\": \"$ISSUE_NUMBER\" }"
